### PR TITLE
doc(readme): add shields with repo url

### LINKED ISSUE #15: Track the stars automatically
I found that the stars of projects listed on it are different to the actual one because of the time.
Hope that someone can help track the stars dynamically.

### PR DESCRIPTION
**Pull request by liuderchi**
- fixes #15 
- total matches: 942 ~~939~~
  - with regex `/(\d{1,}\s?)\|\s?\[@([\w-]+)\]\((.*)\)\/\[\*\*(.*)\*\*\]/g`

NOTE:

To avoid __small badge__ by default layout (as shown below) I added a word "Stargazers" in table head to _extend first column width_.

Before:

demo

After:

demo2

### CODE REVIEW

**Comment by liuderchi** [comment]
@hueitan I forgot to added an enhancement:

__Use emoji when image is failed to display__

Currently it shows repo name, 
but I think it would be better to show only one simple emoji

like this:

demo3

If you want to apply such changes you may do a cherry pick on [my fork](https://github.com/liuderchi/made-in-taiwan/commit/490de64a1558269dad8e05eeb9b25d6572f769cf) 490de64a1

**Comment by hueitan** [comment]
I'm thinking of remove the star number, it takes too much time loading the page.

**Comment by liuderchi** [comment]
@hueitan [shields.io](https://shields.io/) provide a option _Cache Control_

For example from shields.io I entered url of this repo then got this:

`https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?maxAge=2592000`

stars

Providing a _30-day cache_ by specifying `maxAge=259200`

**Comment by hueitan** [comment]
Cool! Didn’t know that.
Could you please update it?

**Comment by liuderchi** [comment]
No prob. What's your preferred cache age?

**Comment by hueitan** [comment]
what about 7 days? one week.

**Pull request merged**
